### ISSUE TITLE
Venetian blinds unreliable

### ISSUE THREAD

**Issue by abra03brand** [AdyRock/com.somfy.tahoma#18]
I have 6 somfy venetian blinds connected through a somfy tahoma box. During week days I use a homey flow (time and day triggered) to activate a wake up scenario inside Tahoma, which works flawless. I have used in the weekend flow (time and day triggered) inside Homey the same scenario and I do not get it to work. The following things I have tried:
1) activating a scenario in Tahoma --> no success (running a test on the flow was successful)
2) activating the venetian blinds individually directly from Homey --> unsuccessful
3) creating a new flow and activating a scenario in Tahoma plus radio --> no Tahoma activity but radio turns on
4) creating a new flow and activating the venetian blinds directly from Homey plus radio --> no Tahoma activity but radio turns on (manual trigger about 30 min later, does trigger the blinds successfully.

Anyone an idea on how to resolve this, seemingly unstructured, failure of execution?

**Comment by AdyRock** [comment]
What version of the app are you using?
Could you enable the Information log, perform an unsuccessful operation and then send me the log. Hopefully I can see if any errors are reported.

**Comment by abra03brand** [comment]
Hi Adrian,

I’m using version2.1.33. The problem occurs over the weekend, I will send you the logs afterwards.

I thought the logging is done automatically, where can I enable the log?

Kind regards,

André

Met vriendelijke groeten,

André

________________________________

**Comment by AdyRock** [comment]
In the App Configuration page, where you enter your Somfy credentials, there is a tab for the Information Log. On that tab is a check box you can tick. When it's not tick it just records critical errors.

**Comment by abra03brand** [comment]
Thanks, I will share the log as explained earlier.

Kind regards,

André Brand
________________________________

**Comment by abra03brand** [comment]
Hi Adrian,

I have send the diagnostic report and received this code:

426b6b66-6905-4db6-8002-5a6218da3a63

I hope you are able to tease out the problem.

Kind regards,

André

Met vriendelijke groeten,

André

________________________________

**Comment by AdyRock** [comment]
I have received the log, and thank you for the description in it plus following up. So many users send me logs with no explanation and no further contact, which leaves me guessing what it's all about, so this is a refreshing change. 
The log is very large so it will take me a bit of time to analyse it and I will need to do it on a bigger screen than my phone.
A quick look at it on a small screen is not showing any problems, as everything is processing normally.

**Comment by abra03brand** [comment]
Hi Andy,

Your welcome, I thankful for your support and if there are other ways that I can help, let me know.

The fact that there is a difference between a manual trigger and the automated one is odd, especially as part of the flow is executed as normal in both ways.

Looking forward to hear from you.

Kind regards, André

Met vriendelijke groeten,

André

________________________________

**Comment by AdyRock** [comment]
Looking at the log on a big screen identified an issue pretty quickly. I'm not sure if it's the cause of the problem you experienced, but it is certainly related.

```
Unhandled Rejection at: Promise {
     < rejected > TypeError: this.triggerTiltChange is not a function
    at ExteriorVenetianBlindDevice.onCapabilityWindowcoveringsTiltSet(/drivers/WindowCoveringsDevice.js: 343: 25)
```

I have published a new test version for you to try: https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

Let me know if you still have the problem with the new version.

**Comment by abra03brand** [comment]
I have installed the update and will let you know the result tomorrow morning.

Have a good one.

Kind regards,
André

Kind regards,

André Brand
________________________________

**Comment by abra03brand** [comment]
Hi Adrian,

Unfortunately the problem still occurs in the same way as yesterday morning. Do you want me to send you a new log?

Kind regards, André

Met vriendelijke groeten,

André

________________________________

**Comment by AdyRock** [comment]
Yes please. 
At what time where the meant to open?

**Comment by abra03brand** [comment]
Hi Adrian,

3d75661c-359b-40a8-b56e-ce6a724b06ad.

The blinds are due to open at 8am. They open at 7 during weekdays. At that time I use the sceanrio “wakker” in Tahoma. I started using that for the weekend flow as well, unsuccessfully. I change the scenario to an individual command directly from Homey for each blind individually. No change in success.

Kind regards, André

Met vriendelijke groeten,

André

________________________________

**Comment by AdyRock** [comment]
Unfortunately, the first entry in the log is at 8:31 UTC so it would have lost the information around the time it was supposed to have happened. What is your time difference from UTC?
I must admit it is very puzzling that it works at 7am during the week and not at 8am on a weekend. Does it work if you schedule the flow for 8:05. Just wondering if there is something else happening at 8am that blocks the commands!
If possible next weekend, could you send the log from the App Configuration page at 8:01. I think my log will hold more information than Athom log in a crash report.

**Comment by abra03brand** [comment]
Hi Adrian, there is one hour time difference between UTC and CET, where I am. I have had the same thought. Will change it for the coming weekend and will let you know accordingly.

Kind regards,

André

Met vriendelijke groeten,

André

________________________________

**Comment by abra03brand** [comment]
Hi Adrian,

The 3 minutes delay did the trick this morning.
8379ac52-a044-46f9-8624-e91e5ac5af55

It is an acceptable solution to me, although it is still a work around. Are you able to pinpoint the issue? Or aware of any similar issues?

Thanks a lot door your support and quick follow up. Very much valued and appreciated.

Kind regards,

André


Kind regards,

André Brand
________________________________

**Comment by AdyRock** [comment]
I still have managed to figure out what goes wrong at 8:00 so can only think that lots of users also do things at that time which puts a large load on the servers. 
If you need any further help on this then please get back to me but for now I will close the issue.
