### ISSUE TITLE
Support in Homey for AC (Naviclim)

### ISSUE THREAD

**Issue by LukDG** [AdyRock/com.somfy.tahoma#198]
Hey, is there a way to add support in Homey for an AC (module) from Somfy that supports Naviclim modules in AC's ? 
thx!

![Afbeelding van WhatsApp op 2024-11-30 om 14 28 48_a3382d0d](https://github.com/user-attachments/assets/c6f2cb21-6c92-4696-a632-0dc909072233)
![Afbeelding van WhatsApp op 2024-11-30 om 14 28 48_8a9fb492](https://github.com/user-attachments/assets/c758115a-919a-4222-8812-dfd4ae7d0208)

**Comment by AdyRock** [comment]
If you have added them to a Tahoma, etc, then I should be able to pick it up and add a driver for it. 
Could you open the app settings page and select the Device Log, then tap on Get Log followed by Send Log once the list has populated.

**Comment by LukDG** [comment]
Done

**Comment by AdyRock** [comment]
I have received the log, and it looks 👌 
I will add support as soon as I can.

**Comment by LukDG** [comment]
I can see the devices now in Homey, but I can't control them with flows ?

**Comment by LukDG** [comment]
Hi 

> I have received the log, and it looks 👌 I will add support as soon as I can.

Can I provide new logs to control them with flows ? i can only read values and set via dashboard, but not via flows?

**Comment by AdyRock** [comment]
Sorry for the delay. I will take a look as I can't remember what was implemented, but I should be able to add the Flows support from the capabilities.

**Comment by LukDG** [comment]
Hey, any news about flow support and Somfy/Naviclim AC module?
Do you need new logs tot capture the capabilities?
Luk

**Comment by LukDG** [comment]
Hey,

Is there any update about controlling the AC with flows? 
I can control them via Homey, but not via flows in Homey

Thx!

**Comment by AdyRock** [comment]
So sorry for the delay but my wife was diagnosed with bowel cancer last November so my mind was not focused. Good news is she is now all clear and I have published a new test version that should have all the Flow action cards for the AC.

**Comment by LukDG** [comment]
Sorry to hear that Adrian, glad to know that it's all good now! I have send an event log. If i try to set the AC to cooling via flows I get an error.

**Comment by AdyRock** [comment]
I'm not seeing any errors in the event log.
What errors are you seeing?

Can you enable the information log and then send that after seeing the error?

**Comment by LukDG** [comment]
Done

![Image](https://github.com/user-attachments/assets/ebd9483a-04ad-4df7-b476-37f36286fed1)

**Comment by AdyRock** [comment]
Sorry, I'm still not seeing any errors in the log. If you touch the red triangle, do you see an error message?

**Comment by LukDG** [comment]
![Image](https://github.com/user-attachments/assets/8f4e5726-0d85-4ae7-8d37-b1027a0656d3)

**Comment by LukDG** [comment]
![Image](https://github.com/user-attachments/assets/0e34d8c4-3150-4b0f-a7ae-660e5cc53b01)
![Image](https://github.com/user-attachments/assets/efff6fb5-5422-49cb-9e42-15c2f56fda1f)

**Comment by LukDG** [comment]
Hi Adrian, the set temperaturen are the only actions that works.

**Comment by AdyRock** [comment]
OK, I think I failed there then. I will take a look soon.

**Comment by AdyRock** [comment]
OK, that's the problem with not having devices to test on, so thanks for your patience.
I have published a new test version that should hopefully fix those errors.

**Comment by LukDG** [comment]
If there is anything I can do via remote access or... Let me know

**Comment by LukDG** [comment]
Hi, almost there. No red triangle, flow card is working but the AC doesnt execute the action. So if u check the device in Homey it says that it is off but it isn't, if i change the device in Homey to off it does, but not via flows

**Comment by LukDG** [comment]
hmm seems like the error message is 'args.device.onCapabilityThermostatMode is not a function' is not always popping up after some more testing.

**Comment by LukDG** [comment]
<img width="1905" height="1030" alt="Image" src="https://github.com/user-attachments/assets/52a59ff3-dd7b-4624-91e6-52d31ab63a84" />

**Comment by AdyRock** [comment]
OK, got it, a new test version is in the store.
It seems I added an extra 'e' to Thermostat when I created the functions (onCapabilityThermostateMode).

**Comment by LukDG** [comment]
Yes! Thx!

<img width="1370" height="951" alt="Image" src="https://github.com/user-attachments/assets/32512f9e-9674-48bd-937f-169bb0827de9" />

**Comment by LukDG** [comment]
Hey Adrian, is there a possibility to read out the core:Temperature state (periodically) of the device and give it to the device in Homey?   : 
`   "name": "core:TemperatureState",
              "type": 2,
              "value": 23.75`

<img width="393" height="757" alt="Image" src="https://github.com/user-attachments/assets/e764e402-8396-435e-b8fe-249f70246d7c" />

**Comment by LukDG** [comment]
Hey Adrian, the setFanMode is returning failed, i have send a log.
