### ISSUE TITLE
Add support for io:AwningValanceIOComponent

### ISSUE THREAD

**Issue by jseverinson** [AdyRock/com.somfy.tahoma#4]
Hi Adrian! Now I found your repository. :) Thank you a million times for picking this app up and giving it love.

I have six awnings out of which five are not recognized. Looking through the device log I find that they are of the type io:AwningValanceIOComponent. A quick google search shows this type was added to Home Assistant a year ago, so fairly new I believe. It's a regular awning, used on a smaller window. Similar to these ones:
https://lh3.googleusercontent.com/proxy/Tk7KAWvXC5LeTN1p0E6THFL9qUXHKpY6le5L14VJf0lAZNi9JTHzB3cJ2SHHqjI4uu8MVc9Ab7wWcUCQN8UguC6kseri1DzVa6hRgBEGZb_g5EJX9DGE6Ts

Sending the device log gave me an error but I could copy/paste it into an email to myself, so here it is on a pastebin:
https://pastebin.pl/view/1aceb29d

If you look at device 7, labeled "Kök", you'll see one of these. Device 8, labeled "Altan" is the one recognized for comparison.

If you would be able to add support for this "AwningValanceIOComponent" that would be highly appreciated.

**Comment by AdyRock** [comment]
Hi,
Did you install from the Homey Community Store or by downloading from github and installing via the CLI?
I'm just wondering why sending the log gave an error. If you downloaded from git then it will be missing the secret keys.

The new version is now in the store with support for your awnings https://store.homey.community/app/com.somfy.tahoma

**Comment by jseverinson** [comment]
Wow, thank you! I'll test that in a moment. Meanwhile here's a log entry of the connection error, it remains in the new v1.6.16. I downloaded from the Community Store. 

![IMG_6168](https://user-images.githubusercontent.com/4082348/92301701-05216a00-ef66-11ea-9007-b00f7396e82a.png)

**Comment by jseverinson** [comment]
I tested the new version now and it works like a charm to add the new awnings. However I can't control the newly created devices. When opening the controls it shows a default state of 50% and regardless what I set it to, or which up/down/my button I press, nothing happens. Would it help sending a device log for this?

**Update:** Never mind, I am an idiot. The remote controls were in manual mode. When setting them to Auto I can control the awnings from Homey. Thank you a million times!

**Comment by AdyRock** [comment]
Hmm, looks like send is failing because the DNS is failing as it is try to use the looback address. I am now hard coding the IP address to see if that fixes it so could you try to send again with the new version.

I have published a new version. It seems it was more than just the type id that is different to the other awnings. Hopefully I now have the correct endpoints.

**Comment by jseverinson** [comment]
Happy to test, although the installation from the community store now says:

```
Due to an error, the app could not be installed
invalid_checksum
```

**Comment by AdyRock** [comment]
I have published it again and it has installed OK for me from the store so could you try it again?

**Comment by jseverinson** [comment]
I've tried uninstalling the app and rebooting the Homey but I still get the same error message?

**Edit:** Installing v1.6.16 works fine.

**Comment by AdyRock** [comment]
Hmm, sorry about this. I have bumped the version number and uploaded it again. It seems something is corrupted in 17 that is not being replaced by overwriting. Hopeful as this is completely fresh it will be better.

**Comment by jseverinson** [comment]
No need to be sorry, you're helping me and not the other way around. 😊 The v1.6.18 installed like a charm!

Bad news is though that the "Send log" feature still gives an error message, same error log as before. Not a must-have feature for me but I understand you might want it to facilitate requests in the future.

**Comment by AdyRock** [comment]
OK, thanks for trying the log. I will investigate that some more later. I use the same feature in some of my other apps and it has worked well so I'm not sure if I have missed something when adding it to this app or if it is something about your setup. I also have another method in mind that I want to try at some point as it will not require a couple of libraries which will reduce the app size.

The main thing though is does it now control you awnings OK?

**Comment by jseverinson** [comment]
Works very well, thank you!
